<<<<<<< HEAD
sdk: "/Library/InsiteRhoMobile/rhodes"
=======
sdk: "/Library/ParivedaInsite/rhodes"
>>>>>>> 12a9d4c87442b7eb871695b2bfe93139a0f74fd8
sdkversion: 2.3.0
name: InsiteMobile-rhodes
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator4.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.InsiteMobile-rhodes
  BundleURLScheme: InsiteMobile-rhodes

extensions: ["json", "another-extension", "fileutils", "mspec"]
